### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [yamana-runteq41/eigoemon#116]
@yamana-runteq41 
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

```
1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

## READMEから課題解決する実装がされているか&動いている
クイズ機能や用語の学習もできていますね、世界観もとてもいいです！

## 静的コードチェックが入っている
しっかりチェックが入っていますね、引き続きrubocopを使ってコードの可読性を担保しておきましょう。

## 就活において十分な技術力を示せる機能を実装しているか
基本的な部分はとてもいいですね、就活を踏まえるとプラスアルファの機能がほしいところです。
本リリースまでに追加機能にある復習機能など、ユーザーのデータを利用した機能を実装するようにしましょう！

下記に気になった点を挙げたのでご確認ください。

- ルーティングでexplanationsのprogrammingとenglish部分は同じshowアクションにしてパラメータで情報の出しわけをするといいですね
- tutorials_controllerで[1,4,7]の数字を繰り返し利用している&マジックナンバーで利用しているので、使いまわせるように定数で定義しましょう。（マジックナンバーになってる）
- 同じくtutorials_controllerのif文のロジックも同じものが複数あるのでprivateメソッドで定義して使うようにしましょう。
- quizzes_controllerのhandle_level_upのif文がtrueになる処理も1つのメソッドにしてあげるといいですね。
- userモデルファイルの数字使ってる部分も定数で定義してあげましょう。
- boldableモジュールのファイルのリファクタができるかと思うのでチャレンジしてみましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
全体的に完成度は高いですね！
下記に気になった点を挙げたのでご確認ください。

- 問題を解いた後に次の問題へ行く導線がちょっとわかりにくいので、youglish動画側ではなく、問題の解説側においてみるといいかもです（色々試してみてください。）
- 回答のボタンをクリックするときに、ボタン全体がアクティブではなさそうなので、ボタン全体がクリックできるようにしましょう。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by yamana-runteq41** [comment]
@kerochelo 
レビューありがとうございます。

本リリースは9/10までに、復習機能2（誤答パターンの抽出）を除いた全実装を行って実施しようと考えています。
その後9/17までに復習機能2を追加で実装したいと考えています。

よろしくお願いいたします。

**Comment by kerochelo** [comment]
@yamana-runteq41 
OKです！引き続き頑張って実装進めてきましょう:+1:
